[tool.poetry]
name = "eptestbenchmanager"
version = "0.1.0"
description = ""
authors = ["Eric <eric@souder.ca>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pyyaml = "^6.0.2"
epcomms = {path = "../EPComms/dist/epcomms-0.1.0-py3-none-any.whl"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
