name: Build and Publish Poetry Package

on:
  push:
    branches:
      - main

jobs:
  release:
    if: startsWith(github.event.head_commit.message, 'release v')
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Adjust the Python version if needed

      # Install Poetry
      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      # Install dependencies
      - name: Install dependencies
        run: poetry install --no-root

      # Build the package
      - name: Build package
        run: poetry build

      # Create a GitHub release
      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: ${{ github.event.head_commit.message }}
          body: |
            This release is automatically generated from the merge request.
          draft: false
          prerelease: false

      # Upload the package artifact to the release
      - name: Upload package to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/*.whl
          asset_name: ${{ github.event.head_commit.message }}.whl
          asset_content_type: application/zip
